export const FETCH_AUTOS_START = 'FETCH_AUTOS_START'
export const FETCH_AUTOS_SUCCESS = 'FETCH_AUTOS_SUCCESS'
export const FETCH_AUTOS_FAILURE = 'FETCH_AUTOS_FAILURE'

export const LOAD_MORE_AUTOS_START = 'LOAD_MORE_AUTOS_START'
export const LOAD_MORE_AUTOS_SUCCESS = 'LOAD_MORE_AUTOS_SUCCESS'
export const LOAD_MORE_AUTOS_FAILURE = 'LOAD_MORE_AUTOS_FAILURE'

export const FETCH_AUTO_BY_ID_START = 'FETCH_AUTO_BY_ID_START'
export const FETCH_AUTO_BY_ID_SUCCESS = 'FETCH_AUTO_BY_ID_SUCCESS'
export const FETCH_AUTO_BY_ID_FAILURE = 'FETCH_AUTO_BY_ID_FAILURE'

export const ADD_AUTO_TO_BASKET = 'ADD_AUTO_TO_BASKET'

export const SEARCH_AUTO = 'SEARCH_AUTO'

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'


export const ADD_NEW_AUTO_START = 'ADD_NEW_AUTO_START'
export const ADD_NEW_AUTO_SUCCESS = 'ADD_NEW_AUTO_SUCCESS'
export const ADD_NEW_AUTO_FAILURE = 'ADD_NEW_AUTO_FAILURE'
